apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ankr-net-third
  namespace: kube-system
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ankr-net-third",
    "type": "macvlan",
    "master": "eno1",
    "mode": "vepa",
    "ipam": {
    "type": "opennet",
    "range": [
       {
          "subnet":"95.168.188.0/26",
          "start":"95.168.188.151",
          "end":"95.168.188.181",
          "gw":"95.168.188.190",
          "dev":"80197"
       },
       {
          "subnet":"23.19.61.0/25",
          "start":"23.19.61.1",
          "end":"23.19.61.32",
          "gw":"23.19.61.126",
          "dev":"80198"
       },
       {
          "subnet":"23.19.61.0/26",
          "start":"23.19.61.129",
          "end":"23.19.61.160",
          "gw":"23.19.61.190",
          "dev":"80201"
       },
       {
          "subnet":"23.19.61.0/25",
          "start":"23.19.61.33",
          "end":"23.19.61.64",
          "gw":"23.19.61.126",
          "dev":"80203"
       },
       {
          "subnet":"23.19.61.0/25",
          "start":"23.19.61.65",
          "end":"23.19.61.96",
          "gw":"23.19.61.126",
          "dev":"80204"
       },
       {
          "subnet":"95.168.188.0/26",
          "start":"95.168.188.214",
          "end":"95.168.188.245",
          "gw":"95.168.188.254",
          "dev":"80208"
       },
       {
          "subnet":"23.19.61.0/26",
          "start":"23.19.61.161",
          "end":"23.19.61.187",
          "gw":"23.19.61.190",
          "dev":"80363"
       },
       {
          "subnet":"23.19.61.0/26",
          "start":"23.19.61.193",
          "end":"23.19.61.197",
          "gw":"23.19.61.222",
          "dev":"80363"
       },
       {
          "subnet":"23.19.61.0/27",
          "start":"23.19.61.198",
          "end":"23.19.61.219",
          "gw":"23.19.61.222",
          "dev":"80364"
       },
       {
          "subnet":"23.19.61.0/27",
          "start":"23.19.61.225",
          "end":"23.19.61.234",
          "gw":"23.19.61.254",
          "dev":"80364"
       },
       {
          "subnet":"23.19.61.0/25",
          "start":"23.19.61.97",
          "end":"23.19.61.123",
          "gw":"23.19.61.126",
          "dev":"80366"
       },
       {
          "subnet":"95.168.188.0/26",
          "start":"95.168.188.182",
          "end":"95.168.188.186",
          "gw":"95.168.188.190",
          "dev":"80366"
       }
     ],
    "dns":{
      "nameserver":[
        "8.8.8.8",
        "8.8.4.4"
      ]
    }
    }
}'